<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesignPatternsDemo.Domain\DesignPatternsDemo.Domain.csproj" />
    <ProjectReference Include="..\DesignPatternsDemo.Integrations\DesignPatternsDemo.Integrations.csproj" />
    <ProjectReference Include="..\DesignPatternsDemo.Prototypes\DesignPatternsDemo.Prototypes.csproj" />
  </ItemGroup>

</Project>
